/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.github.filiperobot.challengeonebackendconversor.views;

import com.github.filiperobot.challengeonebackendconversor.controllers.ConversorDeMoedasController;
import com.github.filiperobot.challengeonebackendconversor.views.componests.OptionPane;

import java.util.Objects;

/**
 *
 * @author FilipeRobot
 * @GitHub <a href="https://github.com/FilipeRobot">GitHub Profile</a>
 */
public class ConversorDeMoedas extends javax.swing.JInternalFrame {

    private final ConversorDeMoedasController controller;

    /**
     * Creates new form ConversorDeMoedas
     */
    public ConversorDeMoedas() {
        initComponents();
        this.controller = new ConversorDeMoedasController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxTipoDeMoeda = new javax.swing.JComboBox<>();
        jLabelValorParaConversao = new javax.swing.JLabel();
        jTextFieldValorParaConversao = new javax.swing.JTextField();
        jButtonConverter = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldValorConvertido = new javax.swing.JTextField();
        jButtonCopiarValor = new javax.swing.JButton();
        jButtonCopiarTudo = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMaximizable(true);
        setTitle("Conversor de Moedas");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setText("Qual o tipo de moedas você deseja converter?");

        jComboBoxTipoDeMoeda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Real para Dolar", "Real para Euro", "Real para Libras Esterlinas", "Real para Peso Argentino", "Real para Peso Chileno", "Dolar para Real", "Euro para Real", "Libras Esterlinas para Real", "Peso Argentino para Real", "Peso Chileno para Real" }));
        jComboBoxTipoDeMoeda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoDeMoedaActionPerformed(evt);
            }
        });

        jLabelValorParaConversao.setText("Informe o valor para a conversão: ");

        jTextFieldValorParaConversao.setText("Informe valor para converter");
        jTextFieldValorParaConversao.setToolTipText("1000,00");
        jTextFieldValorParaConversao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldValorParaConversaoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldValorParaConversaoFocusLost(evt);
            }
        });

        jButtonConverter.setText("Converter");
        jButtonConverter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConverterActionPerformed(evt);
            }
        });

        jLabel4.setText("Valor convertido:");

        jTextFieldValorConvertido.setEditable(false);
        jTextFieldValorConvertido.setToolTipText("<html>\nVocê pode copiar toda a menssagem interagindo<br/>\ncom ela ou apenas clicar no botão para copiar apenas<br/>\no valor convertido\n</html>");

        jButtonCopiarValor.setText("Copiar valor");
        jButtonCopiarValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCopiarValorActionPerformed(evt);
            }
        });

        jButtonCopiarTudo.setText("Copiar tudo");
        jButtonCopiarTudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCopiarTudoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxTipoDeMoeda, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelValorParaConversao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldValorParaConversao, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonConverter, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldValorConvertido, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCopiarTudo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCopiarValor)
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxTipoDeMoeda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelValorParaConversao)
                    .addComponent(jTextFieldValorParaConversao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConverter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldValorConvertido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCopiarValor)
                    .addComponent(jButtonCopiarTudo))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        controller.fechaConversorDeMoedas(this);
    }//GEN-LAST:event_formInternalFrameClosing

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        String itemSelecionadoNome = Objects.requireNonNull(jComboBoxTipoDeMoeda.getSelectedItem()).toString();
        String texto = controller.mudarTextoLabelValorParaConversaoTeste(itemSelecionadoNome);

        jLabelValorParaConversao.setText(texto);
    }//GEN-LAST:event_formInternalFrameOpened

    private void jComboBoxTipoDeMoedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoDeMoedaActionPerformed
        jTextFieldValorConvertido.setText("");

        String itemSelecionadoNome = Objects.requireNonNull(jComboBoxTipoDeMoeda.getSelectedItem()).toString();

        String texto = controller.mudarTextoLabelValorParaConversaoTeste(itemSelecionadoNome);

        jLabelValorParaConversao.setText(texto);
    }//GEN-LAST:event_jComboBoxTipoDeMoedaActionPerformed

    private void jButtonConverterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConverterActionPerformed
        String itemSelecionadoNome = Objects.requireNonNull(jComboBoxTipoDeMoeda.getSelectedItem()).toString();
        String valor = jTextFieldValorParaConversao.getText().trim();

        if(valor.isEmpty() || valor.isBlank() || valor.compareTo("Informe valor para converter") == 0) {
            OptionPane.erroMessage("Valor não informado");
            return;
        }

        jTextFieldValorConvertido.setText(controller.converter(itemSelecionadoNome, valor));
    }//GEN-LAST:event_jButtonConverterActionPerformed

    private void jButtonCopiarValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCopiarValorActionPerformed
        String itemSelecionadoNome = Objects.requireNonNull(jComboBoxTipoDeMoeda.getSelectedItem()).toString();
        try {
            if (jTextFieldValorConvertido.getText().trim().isEmpty() || jTextFieldValorConvertido.getText().trim().isBlank()){
                OptionPane.erroMessage("Nenhum valor para copiar");
                return;
            }
            controller.copiar(jTextFieldValorConvertido.getText(), itemSelecionadoNome);
            OptionPane.okMessage("Texto copiado com sucesso!");
        } catch (Exception exception) {
            OptionPane.erroMessage(exception.getMessage());
        }
    }//GEN-LAST:event_jButtonCopiarValorActionPerformed

    private void jButtonCopiarTudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCopiarTudoActionPerformed
        try {
            if (jTextFieldValorConvertido.getText().trim().isEmpty() || jTextFieldValorConvertido.getText().trim().isBlank()){
                OptionPane.erroMessage("Nenhum valor para copiar");
                return;
            }
            controller.copiarTudo(jTextFieldValorConvertido.getText());
            OptionPane.okMessage("Texto copiado com sucesso!");
        } catch (Exception exception) {
            OptionPane.erroMessage(exception.getMessage());
        }
    }//GEN-LAST:event_jButtonCopiarTudoActionPerformed

    private void jTextFieldValorParaConversaoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldValorParaConversaoFocusGained
        jTextFieldValorParaConversao.setText("");
    }//GEN-LAST:event_jTextFieldValorParaConversaoFocusGained

    private void jTextFieldValorParaConversaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldValorParaConversaoFocusLost
        String texto = jTextFieldValorParaConversao.getText().trim();
        if(texto.isBlank() || texto.isEmpty()){
            jTextFieldValorParaConversao.setText("Informe valor para converter");
        }
    }//GEN-LAST:event_jTextFieldValorParaConversaoFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConverter;
    private javax.swing.JButton jButtonCopiarTudo;
    private javax.swing.JButton jButtonCopiarValor;
    private javax.swing.JComboBox<String> jComboBoxTipoDeMoeda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelValorParaConversao;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldValorConvertido;
    private javax.swing.JTextField jTextFieldValorParaConversao;
    // End of variables declaration//GEN-END:variables
}
